version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-marlin}
      POSTGRES_USER: ${POSTGRES_USER:-marlin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    env_file:
      - .env            # copy from .env.sample and tweak
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app  # live-reload friendly
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata: 